function pipe<A>(value: A): A;
function pipe<A, B>(value: A, fn1: (a: A) => B): B;
function pipe<A, B, C>(value: A, fn1: (a: A) => B, fn2: (b: B) => C): C;
function pipe<A, B, C, D>(
	value: A,
	fn1: (a: A) => B,
	fn2: (b: B) => C,
	fn3: (c: C) => D,
): D;
function pipe<A, B, C, D, E>(
	value: A,
	fn1: (a: A) => B,
	fn2: (b: B) => C,
	fn3: (c: C) => D,
	fn4: (d: D) => E,
): E;
function pipe<A, B, C, D, E, F>(
	value: A,
	fn1: (a: A) => B,
	fn2: (b: B) => C,
	fn3: (c: C) => D,
	fn4: (d: D) => E,
	fn5: (e: E) => F,
): F;
function pipe<A, B, C, D, E, F, G>(
	value: A,
	fn1: (a: A) => B,
	fn2: (b: B) => C,
	fn3: (c: C) => D,
	fn4: (d: D) => E,
	fn5: (e: E) => F,
	fn6: (f: F) => G,
): G;
function pipe<A, B, C, D, E, F, G, H>(
	value: A,
	fn1: (a: A) => B,
	fn2: (b: B) => C,
	fn3: (c: C) => D,
	fn4: (d: D) => E,
	fn5: (e: E) => F,
	fn6: (f: F) => G,
	fn7: (g: G) => H,
): H;
function pipe<A, B, C, D, E, F, G, H, I>(
	value: A,
	fn1: (a: A) => B,
	fn2: (b: B) => C,
	fn3: (c: C) => D,
	fn4: (d: D) => E,
	fn5: (e: E) => F,
	fn6: (f: F) => G,
	fn7: (g: G) => H,
	fn8: (h: H) => I,
): I;
function pipe<A, B, C, D, E, F, G, H, I, J>(
	value: A,
	fn1: (a: A) => B,
	fn2: (b: B) => C,
	fn3: (c: C) => D,
	fn4: (d: D) => E,
	fn5: (e: E) => F,
	fn6: (f: F) => G,
	fn7: (g: G) => H,
	fn8: (h: H) => I,
	fn9: (i: I) => J,
): J;
function pipe<A, B, C, D, E, F, G, H, I, J, K>(
	value: A,
	fn1: (a: A) => B,
	fn2: (b: B) => C,
	fn3: (c: C) => D,
	fn4: (d: D) => E,
	fn5: (e: E) => F,
	fn6: (f: F) => G,
	fn7: (g: G) => H,
	fn8: (h: H) => I,
	fn9: (i: I) => J,
	fn10: (j: J) => K,
): K;
function pipe<A, B, C, D, E, F, G, H, I, J, K, L>(
	value: A,
	fn1: (a: A) => B,
	fn2: (b: B) => C,
	fn3: (c: C) => D,
	fn4: (d: D) => E,
	fn5: (e: E) => F,
	fn6: (f: F) => G,
	fn7: (g: G) => H,
	fn8: (h: H) => I,
	fn9: (i: I) => J,
	fn10: (j: J) => K,
	fn11: (k: K) => L,
): L;
function pipe<A, B, C, D, E, F, G, H, I, J, K, L, M>(
	value: A,
	fn1: (a: A) => B,
	fn2: (b: B) => C,
	fn3: (c: C) => D,
	fn4: (d: D) => E,
	fn5: (e: E) => F,
	fn6: (f: F) => G,
	fn7: (g: G) => H,
	fn8: (h: H) => I,
	fn9: (i: I) => J,
	fn10: (j: J) => K,
	fn11: (k: K) => L,
	fn12: (l: L) => M,
): M;
function pipe<A, B, C, D, E, F, G, H, I, J, K, L, M, N>(
	value: A,
	fn1: (a: A) => B,
	fn2: (b: B) => C,
	fn3: (c: C) => D,
	fn4: (d: D) => E,
	fn5: (e: E) => F,
	fn6: (f: F) => G,
	fn7: (g: G) => H,
	fn8: (h: H) => I,
	fn9: (i: I) => J,
	fn10: (j: J) => K,
	fn11: (k: K) => L,
	fn12: (l: L) => M,
	fn13: (m: M) => N,
): N;
function pipe<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O>(
	value: A,
	fn1: (a: A) => B,
	fn2: (b: B) => C,
	fn3: (c: C) => D,
	fn4: (d: D) => E,
	fn5: (e: E) => F,
	fn6: (f: F) => G,
	fn7: (g: G) => H,
	fn8: (h: H) => I,
	fn9: (i: I) => J,
	fn10: (j: J) => K,
	fn11: (k: K) => L,
	fn12: (l: L) => M,
	fn13: (m: M) => N,
	fn14: (n: N) => O,
): O;
function pipe<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P>(
	value: A,
	fn1: (a: A) => B,
	fn2: (b: B) => C,
	fn3: (c: C) => D,
	fn4: (d: D) => E,
	fn5: (e: E) => F,
	fn6: (f: F) => G,
	fn7: (g: G) => H,
	fn8: (h: H) => I,
	fn9: (i: I) => J,
	fn10: (j: J) => K,
	fn11: (k: K) => L,
	fn12: (l: L) => M,
	fn13: (m: M) => N,
	fn14: (n: N) => O,
	fn15: (o: O) => P,
): P;
function pipe<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q>(
	value: A,
	fn1: (a: A) => B,
	fn2: (b: B) => C,
	fn3: (c: C) => D,
	fn4: (d: D) => E,
	fn5: (e: E) => F,
	fn6: (f: F) => G,
	fn7: (g: G) => H,
	fn8: (h: H) => I,
	fn9: (i: I) => J,
	fn10: (j: J) => K,
	fn11: (k: K) => L,
	fn12: (l: L) => M,
	fn13: (m: M) => N,
	fn14: (n: N) => O,
	fn15: (o: O) => P,
	fn16: (p: P) => Q,
): Q;
function pipe<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R>(
	value: A,
	fn1: (a: A) => B,
	fn2: (b: B) => C,
	fn3: (c: C) => D,
	fn4: (d: D) => E,
	fn5: (e: E) => F,
	fn6: (f: F) => G,
	fn7: (g: G) => H,
	fn8: (h: H) => I,
	fn9: (i: I) => J,
	fn10: (j: J) => K,
	fn11: (k: K) => L,
	fn12: (l: L) => M,
	fn13: (m: M) => N,
	fn14: (n: N) => O,
	fn15: (o: O) => P,
	fn16: (p: P) => Q,
	fn17: (q: Q) => R,
): R;
function pipe<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S>(
	value: A,
	fn1: (a: A) => B,
	fn2: (b: B) => C,
	fn3: (c: C) => D,
	fn4: (d: D) => E,
	fn5: (e: E) => F,
	fn6: (f: F) => G,
	fn7: (g: G) => H,
	fn8: (h: H) => I,
	fn9: (i: I) => J,
	fn10: (j: J) => K,
	fn11: (k: K) => L,
	fn12: (l: L) => M,
	fn13: (m: M) => N,
	fn14: (n: N) => O,
	fn15: (o: O) => P,
	fn16: (p: P) => Q,
	fn17: (q: Q) => R,
	fn18: (r: R) => S,
): S;
function pipe<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T>(
	value: A,
	fn1: (a: A) => B,
	fn2: (b: B) => C,
	fn3: (c: C) => D,
	fn4: (d: D) => E,
	fn5: (e: E) => F,
	fn6: (f: F) => G,
	fn7: (g: G) => H,
	fn8: (h: H) => I,
	fn9: (i: I) => J,
	fn10: (j: J) => K,
	fn11: (k: K) => L,
	fn12: (l: L) => M,
	fn13: (m: M) => N,
	fn14: (n: N) => O,
	fn15: (o: O) => P,
	fn16: (p: P) => Q,
	fn17: (q: Q) => R,
	fn18: (r: R) => S,
	fn19: (s: S) => T,
): T;

function pipe(value: unknown, ...fns: Array<(a: unknown) => unknown>): unknown {
	if (fns.length === 0) return value;
	return fns.reduce((acc, fn) => fn(acc), value);
}

export { pipe };

export const identity = <T>(x: T): T => x;
